### ISSUE TITLE
Feature request / suggestion - Sanitization

### ISSUE THREAD

**Issue by jammy-dodgers** [pascalla/clanchat.net#1]
As much as being able to type emojis is kind of funny... 
![image](https://github.com/pascalla/clanchat.net/assets/16457802/84d5fa89-31af-4982-af07-ccfbcf3861f1)
![image](https://github.com/pascalla/clanchat.net/assets/16457802/86318793-4f8a-4fdd-a1e3-b150b4652a1d)

It might be good to add some kind of serverside sanitization (or hell, even clientside on the plugin, since only trusted users would really be using it) since Discord webhooks are free to @ roles and users (including @ everyone, I assume! didn't want to annoy our server by testing that one 😇) if you know the syntax for it!

![image](https://github.com/pascalla/clanchat.net/assets/16457802/1c8ae72f-59d7-44cd-a185-41cef6b5e998)
![image](https://github.com/pascalla/clanchat.net/assets/16457802/1e856daf-d941-47d6-9955-5a33c1538a5a)

**Comment by pascalla** [comment]
Hopefully got all of them!

https://github.com/pascalla/clanchat.net/commit/aa87ef67f00a8379cda7bda6660d3f56d095a182

![image](https://github.com/pascalla/clanchat.net/assets/22846433/d1828dde-f7c5-423d-8604-4e41caa67aef)
![image](https://github.com/pascalla/clanchat.net/assets/22846433/e43ec9f4-a45c-48a4-9eb4-36b614d82a6f)


Appreciate the issue!

**Comment by jammy-dodgers** [comment]
![image](https://github.com/pascalla/clanchat.net/assets/16457802/9ff7a54e-a7ca-46a7-8e0f-42ec31db507b)
![image](https://github.com/pascalla/clanchat.net/assets/16457802/f8f10529-fc70-4ce2-9d92-ff82675e27e0)

Hahah, I've discovered that @ everyone's  don't use any special syntax, so they go through on the webhook despite not looking like an actual @ everyone!

Thanks so much for this plugin and the site, by the way.

**Comment by pascalla** [comment]
Strange that is doesn't highlight the @ everyone as a tag, just as a message. I've made it just append a space between, as I feel like "@ here" and "@ everyone" might actually be used in a clan context.

**Comment by jammy-dodgers** [comment]
![image](https://github.com/pascalla/clanchat.net/assets/16457802/958407b3-fb03-43c9-b360-65d2c77986dc)
![image](https://github.com/pascalla/clanchat.net/assets/16457802/aa9f927f-25d7-4be2-94dd-bffc26b675fa)

![image](https://github.com/pascalla/clanchat.net/assets/16457802/fa5601ee-0908-4a93-8ed8-6dd0445e214d)

Oops! Sorry for causing so many problems :P
You got a page like a paypal or ko-fi for donations or anything?

**Comment by pascalla** [comment]
I knew what I signed up for when interacting with the greatest QA team, the Runescape player base :) Not looking for any donations for the time being!

Added some more precautions!
