### ISSUE TITLE
FYI: Webhooks can post named links

### ISSUE THREAD

**Issue by jammy-dodgers** [pascalla/clanchat.net#3]
This one's more of an informational thing, though you may consider it a possible issue. I wasn't even aware this markdown functionality was supported in discord. Regular users can't post it, but I guess webhooks and bots can.
Likely not a big issue as OSRS chat censors links anyway?
![image](https://github.com/pascalla/clanchat.net/assets/16457802/797d46ed-15b5-4fea-903e-80d9038ad9fa)
![image](https://github.com/pascalla/clanchat.net/assets/16457802/d34153d4-7ade-4447-b987-7c02c96f2633)

**Comment by pascalla** [comment]
![image](https://github.com/pascalla/clanchat.net/assets/22846433/a9f0d825-b284-4184-8182-5b1a2cf25a9e)
Hopefully got all the markup!
