### ISSUE TITLE
Quest messages not categorized properly

### ISSUE THREAD

**Issue by maxdeviant** [pascalla/clanchat.net#4]
Hello there!

There appears to be a mismatch between the RuneLite plugin and the server for quest messages.

In the client: https://github.com/pascalla/clan-chat-webhook/blob/8daaad9ed0ea57ba7ef1751f3d8bd36094558b92/src/main/java/com/clanchatwebhook/ClanChatWebhookPlugin.java#L84

On the server: https://github.com/pascalla/clanchat.net/blob/99b371a1a7b931895fc9ab7989db0bd43bd6e58f/app/Models/ClanMessage.php#L60-L63

The result of this is that the quest messages don't appear to be categorized as a message type.

For accounts without chat icons the message is dropped. For accounts that have a chat icon, you get this fun little bug 😄

![image](https://github.com/pascalla/clanchat.net/assets/1486634/8c41da4b-6f5d-44ed-bc40-7ad9074ec280)

**Comment by pascalla** [comment]
https://github.com/pascalla/clan-chat-webhook/issues/3#issuecomment-1565477174

**Comment by pascalla** [comment]
Seen this working correctly on the latest release. Thanks for the bug :)
