### ISSUE TITLE
Add category for clan invite messages

### ISSUE THREAD

**Issue by maxdeviant** [pascalla/clanchat.net#5]
It looks like clan invite messages are currently categorized as normal chat messages.

This results in them showing an empty `**:` at the beginning due to them lacking a username:

![image](https://github.com/pascalla/clanchat.net/assets/1486634/9301afc1-0cb7-4805-a98c-3f69cecc01a2)

I imagine the same would be true for messages when someone leaves the clan.

Would it be possible to categorize these as system messages?

**Comment by pascalla** [comment]
I'm going to put these in the ATTENDANCE (Join/Leave) settings. Just need to check if there is also a kick message. 
![image](https://github.com/pascalla/clanchat.net/assets/22846433/57efe42a-0f3a-4672-a8cd-a14027613d54)

Just as an FYI i'm missing a few categories still, which will be added, Combat Achievements, Clue Rewards and Level Up. Incase you notice those.

**Comment by pascalla** [comment]
> I'm going to put these in the ATTENDANCE (Join/Leave) settings. Just need to check if there is also a kick message. ![image](https://user-images.githubusercontent.com/22846433/241413299-57efe42a-0f3a-4672-a8cd-a14027613d54.png)
> 
> Just as an FYI i'm missing a few categories still, which will be added, Combat Achievements, Clue Rewards and Level Up. Incase you notice those.

This has been done and verified working :)
